version: 0.2
phases:
  install:
    commands:
      - n 16.14
  pre_build:
    commands:
      - echo Running AWS Code Build
      - printf 'REACT_APP_API_URL=%s' $REACT_APP_API_URL > .env
  build:
    commands:
      - echo Build started on `date`s
      - echo Building the Docker image...
      - yarn install
      - yarn run build
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'build'

