version: 0.2
phases:
  install:
    commands:
      - n 16.14
  pre_build:
    commands:
      - echo Running AWS Code Build
      - export TAG=v1.0.0-dev
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - yarn install
      - REACT_APP_API_URL=$API_URL yarn run build
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'build'

